# Welcome to Jekyll!

# Website settings
title: Mit's Blog
description: Mit's blog,use Jekyll and github pages.
keywords: 'Mit,Jalpc,blog,Jekyll,github,gh-pages'
baseurl: ''  # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url: 'https://srcmit.github.io'  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: "http://127.0.0.1:4000"
img_path: '/static/assets/img/blog'  # url should be changed to 'homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation
  name: 'LGZ'
  first_name: 'Li'
  last_name: 'GuoZhen'
  cv: ''
  email: '2235926405@qq.com'
  facebook_username: 'srcmit'
  github_username: 'srcmit'
  avatar: '/static/assets/img/landing/Mit.jpg'
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-angular
    - name: icon-docker
  desc: 'Hi I am a Full Stack-ism, I Like evething about computer Especially Penetration network and machine learning .and i like algorithm, So I recently in the brush problem of Acm , Besides , I like Fundamentals of Computer.'

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-73784599-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id: a49d4901c7853da9


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
